// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BusinessObject.SharedModels.Models;


[Table("user")]
public partial class User
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Column("password")]
    [PasswordPropertyText(true)]
    public string Password { get; set; } = string.Empty;

    [Column("email")]
    [Required]
    [EmailAddress]
    [StringLength(50)]
    public string Email { get; set; } = string.Empty;

    [Column("full_name")]
    [Required]
    [StringLength(50)]
    public string FullName { get; set; } = string.Empty;

    [Column("status")]
    [EnumDataType(typeof(SharedModel.Enums.UserStatus))]
    public SharedModel.Enums.UserStatus Status { get; set; } = SharedModel.Enums.UserStatus.Active;

    [Column("phone_number")]
    [Phone]
    [StringLength(15)]
    public string PhoneNumber { get; set; }

    [Column("role")]
    [EnumDataType(typeof(SharedModel.Enums.UserRole))]
    public SharedModel.Enums.UserRole Role { get; set; } = SharedModel.Enums.UserRole.User;

    [InverseProperty("User")]
    public ICollection<Pond> Ponds { get; set; } = new List<Pond>();
}